language: php

sudo: required

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "ORrc/aGcsjDXVGvgwv9avUK+V/bpCbUHZPByMnEt+MfELtDYfF2GieF6BLGxwUv3sINOL8vEdVK1bMBnUpepVpTb9mWfV2cwE0bFR83dGBZYWhIviWCRIQbtSj+rni5Plda/UZPeuWhDw0Eki4xqjZsncI0igRuJnRLOAKQ4QZs="
    - GIT_COMMITTER_NAME=s-nakajima
    - GIT_COMMITTER_EMAIL=nakajimashouhei@gmail.com
    - GIT_AUTHOR_NAME=s-nakajima
    - GIT_AUTHOR_EMAIL=nakajimashouhei@gmail.com

before_script:
  - pwd
  - ls -al
  - ls -al /home/travis/
  - ls -al /home/travis/.cache/
  - ls -al /home/travis/.cache/pip
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - ls -al
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
